#!/bin/bash
# Submission script for NIC5
#SBATCH --job-name=River_test
#SBATCH --time=00:30:00 # hh:mm:ss
#
#SBATCH --ntasks=16
#SBATCH --mem-per-cpu=2000 # megabytes
#SBATCH --partition=batch
#
#SBATCH --mail-user=acapet@uliege.be
#SBATCH --mail-type=ALL


source envload

mpirun ./coherens
