#!/bin/bash
# Submission script for NIC5
#SBATCH --job-name=River_test
#SBATCH --time=1-00:00:00 # hh:mm:ss
#
#SBATCH --ntasks=9
#SBATCH --nodes=1
#SBATCH --mem-per-cpu=2000 # megabytes
#SBATCH --partition=batch
#
#SBATCH --mail-user=acapet@uliege.be
#SBATCH --mail-type=ALL


source envload

mpirun ./coherens
